version: '2'

volumes:
  data.postgres:
    driver: "local"
  data.opennms:
    driver: "local"

networks:
  net.dc:
      driver: bridge
      ipam:
        config:
          - subnet: 172.29.0.0/16
  net.branch:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.2.0/24
services:
  database:
    image: postgres:9.6
    container_name: demo.horizon.postgres
    env_file:
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5432"
    volumes:
      - data.postgres:/var/lib/postgresql/data
    networks:
      net.dc:
        ipv4_address: 172.29.0.10

  opennms:
    image: opennms/horizon-core-web:latest
    container_name: demo.horizon.core.web
    mem_limit: 3072M
    cap_add:
      - NET_ADMIN
    networks:
      net.dc:
        ipv4_address: 172.29.0.11
    env_file:
      - .opennms.env
      - .postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - database
    volumes:
      - data.opennms:/opennms-data
      - ./etc-overlay:/opt/opennms-etc-overlay
    command: ["-s"]
    ports:
      - "8988:8980"
      - "18980"
      - "1099"
      - "8101"
      - "61616"
      - "5817"
      - "162/udp"

  pris:
    image: opennms/pris:latest
    container_name: demo.pris
    networks:
      net.dc:
        ipv4_address: 172.29.0.8
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./requisitions:/opt/opennms-pris/requisitions
      - ./scriptsteps:/opt/opennms-pris/scriptsteps
    ports:
      - "8000"

  helm:
    image: opennms/helm:latest
    container_name: demo.helm
    networks:
      net.dc:
        ipv4_address: 172.29.0.9
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .grafana.env
    ports:
      - "3000"

  minion:
    image: opennms/minion:latest
    container_name: demo.minion
    networks:
      net.dc:
        ipv4_address: 172.29.0.12
      net.branch:
        ipv4_address: 192.168.2.10
    env_file:
      - .minion.env
    command: ["-c"]
    ports:
      - "8201"
      - "18980"
      - "162/udp"
      - "514/udp"

  dc.srv.01:
    image: indigo/docker-netsnmp
    container_name: dc.srv.01
    networks:
      net.dc:
        ipv4_address: 172.29.0.32
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  dc.srv.02:
    image: indigo/docker-netsnmp
    container_name: dc.srv.02
    networks:
      net.dc:
        ipv4_address: 172.29.0.33
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  dc.web.01:
    image: httpd
    container_name: dc.web.01
    networks:
      net.dc:
        ipv4_address: 172.29.0.34
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"

  branch.srv.01:
    image: indigo/docker-netsnmp
    container_name: branch.srv.01
    networks:
      net.branch:
        ipv4_address: 192.168.2.100
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  branch.srv.02:
    image: indigo/docker-netsnmp
    container_name: branch.srv.02
    networks:
      net.branch:
        ipv4_address: 192.168.2.101
    environment:
      - TZ=Europe/Berlin
    ports:
      - "161/udp"

  branch.web.01:
    image: httpd
    container_name: branch.web.01
    networks:
      net.branch:
        ipv4_address: 192.168.2.102
    environment:
      - TZ=Europe/Berlin
    ports:
      - "80"
