apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: OpenNMS Horizon FM
    orgId: 1

datasources:
- name: OpenNMS Horizon FM
  type: opennms-helm-fault-datasource
  access: proxy
  orgId: 1
  url: http://horizon:8980/opennms
  password:
  user:
  database:
  basicAuth: true
  basicAuthUser: "admin"
  basicAuthPassword: "admin"
  withCredentials: false
  isDefault: false
  version: 1
  editable: false
